# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa038c3e5355f8de5fd8a12baac1cd6c85b920729d456f207c1ab6b0a67f7fba95233f6558be3e81fd3d76f1eef705f71f83e447037ce83655c49e8f5025810a

test:
  secret_key_base: 9bd4b1a744405e1c1967e79de116a02e7b6195a27b56b0f221582188c26a69ed5921df0664b109ea9a9816b7b331df874e966db293ab1efa3281dc16f1673b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
